image: golang:1.18
stages:
  - build
  - test

build:
  stage: build
  script:
    - cd src
    - ./build.sh
  artifacts:
    paths:
      - src/yaml-graph

test:
  stage: test
  dependencies:
    - build
  script:
    - cd src
    - ./test.sh